### ISSUE TITLE
"on-select" returns undefined

### ISSUE THREAD

**Issue by ricricucit** [bouil/angular-google-chart#151]
I'm asynchronously populating a PieChart like this:

var dataPie     = GraphsService.getTopicsPie(customData, $scope.user.datasets[0].app_id, $scope.user.datasets[0].token);

    dataPie.then(function(res) {
      //got it
      pieChartTopics.data = res;
      pieChartTopics.options = {
        legend: 'top',
      };

      pieChartTopics.formatters = {};

      $scope.pieChartTopics = pieChartTopics;
    }, function(reason) {
      //error, give me a reason
    }, function(update) {
      //waiting, give me a message
    });

and i have this line in the directive

    on-select="selectTopic(selectedItem);"

although when selecting something the "selectedItem" is "undefined".

Any idea why?

**Comment by Balrog30** [comment]
Thanks for bringing this to our attention.  I assume you are using the latest version from the gh-pages branch.  If you use the version on master you should be ok.  I merged a pull request based on the idea being good, and without properly reviewing the code.  I'll get this fixed up.

**Comment by ricricucit** [comment]
thank you :+1:
