### ISSUE TITLE
ComboChart

### ISSUE THREAD

**Issue by niclaslindberg** [bouil/angular-google-chart#153]
Hi!

Thanks for the good work!

Is ComboChart supported? Can't get it to work.

**Comment by Balrog30** [comment]
The directive code does very little outside managing the loading of the Google Charts API and asking it to draw your chart.  The only thing that isn't supported so far as I know is the Google Visualization Dashboards and Chart Controls, as this adds another level above the chart.

That being said, if it's not working, it's probably something in your code, and I'd be happy to point you in the right direction if you'd share some of your code.  [Plunker](http://plnkr.co) is great for this as I can quickly see exactly what you're doing in a working environment, but a github gist, or jsfiddle would work well, too.

**Comment by niclaslindberg** [comment]
Thanks Nicholas.

Thanks for answering. I'm sorry for disturbing you with that question! I 
read through the code and saw that it was all there. My data was bad. 
Once again, thanks for your work.

BR

Niclas

*Niclas Lindberg*
Nillsoft AB
Mobile 	+46 (0)734 29 93 11
Office 	+46 (0)44 28 94 60
Address 	Varvsgatan 29
SE-296 33 Åhus
Sweden

**Comment by Balrog30** [comment]
No problem.  Happy to help anytime.

**Comment by niclaslindberg** [comment]
Hi Nicholas.

Could you please remove my contact details from my answer to you in the
forum. Thanks.

**Comment by bouil** [comment]
Done
