### ISSUE TITLE
How to trigger re-size/re-draw from controller

### ISSUE THREAD

**Issue by thuna-garry** [bouil/angular-google-chart#155]
Angular newbie alert!

Following the examples I've got a starting chart working.  The chart is one of many laid-out on the screen each within it own re-sizeable container (or frame).  

```
<li gridster-item="frame" ng-repeat="frame in frames">
....
    <div ng-controller="chartPieCtrl" >
        <div google-chart chart="chart" style="{{chart.cssStyle}}"></div>
    <div>
...
</li>
```
The frame object has x and y properties (along with other chart info that the controller will need).  In the controller I watch for size changes on the enclosing frame, but once I've recognized a frame re-size I don't know how to signal the angular-google-chart to re-size/redraw.

in chartPieCtrl ....

```
    $scope.$watch('frame', function(newVal, oldVal){
        console.log(dumpFrameSize($scope.frame));  //confirm we see the new values
        /**** what code to put here *****/
    }, true);
```
Thank-you for your help.

**Comment by Balrog30** [comment]
The directive watches the chart object's options property.  You can use that to set the width and height of the chart which would cause it to redraw.

**Comment by Balrog30** [comment]
By the way, having logic in your controller that interacts directly with page elements is generally frowned upon in AngularJS.  The reason for this is complicated but has it's roots in Angular's commitment to being testable.  Interactions with the DOM are considered to be very difficult if not impossible to test, so code that does this is usually kept in directives, which makes controllers and services easier to test.  If you have no intention of ever testing then this won't be a problem for you, but if you do then keep this in mind.

**Comment by thuna-garry** [comment]
Yes, that did it.  Seems obvious in hindsight that it would work that way.
Thank-you for your very prompt response.

And yes the next step will be re-factor the code and wrap it up in a directive -- just gotta walk before I run.  Thanks again.
