### ISSUE TITLE
Question: Fixing color to label on series

### ISSUE THREAD

**Issue by eduardopopego** [bouil/angular-google-chart#157]
Hi,

I need to assign a color to each series and maintain that color for each series even after the chart's view is modified.

I'm aware of 'chart.options.series' where you can define colors for each series, but each time you update the chart.view, series move up in the position of chart.options.series and take the color of the previous line.

Example:
$scope.chartObject = {
      'type': 'LineChart',
      'series': {
          0: { color: '#c0392b' },
          1: { color: '#e74c3c'}
      }
};

When chartObject.view = {columns: [0,1,2]}, the colors of the series are 1 and 2 are mapped to 0 and 1.

But when chartObject.view = {columns: [0, 2]}, the color of the series 2 is mapped to 0, instead of 1, thus taking the position of the inactive series on the view.

Is there a simple way of doing this?

Thanks in advance.

**Comment by Balrog30** [comment]
Check out my [blog post](http://nicholasbering.ca/angularjs/2014/08/16/agc-hide-series/) on hiding a series.  The feature I built for that post allows a user to click the legend to hide a series.  It might not be exactly what you're looking for but just see how it's implemented and it might give you some ideas.

**Comment by Balrog30** [comment]
Hi, I posted my suggestion 12 days ago... did it work out for you?  Do you have any further questions?  Is your problem solved?

**Comment by eduardopopego** [comment]
Hi Nicholas, sorry for the delay.

It did give me some ideas but I haven't had time to implement them yet. Thanks for your reply and even though the problem is not solved, I guess you could close the issue.

Regards

**Comment by Balrog30** [comment]
Thanks!  If you still have problems feel free to comment on the closed issue.
