### ISSUE TITLE
Formatting axes

### ISSUE THREAD

**Issue by tcase360** [bouil/angular-google-chart#159]
Hello, I am trying but can't for the life of me format my axes labels and the numbers on mouseover. Here is my code, please tell me what I'm doing wrong. Thank you!

      var dynamicData = [];
      $scope.chartObject = {};
      $scope.chartObject.http = [["January", "2"], ["February", "1594"], ["March", "0"], ["April", "0"], ["May", "0"], ["June", "0"], ["July", "0"], ["August", "0"], ["September", "0"], ["October", "0"], ["November", "0"], ["December", "0"]];
      $scope.length = $scope.chartObject.http.length;
      $scope.chartObject.type = "ColumnChart";
      $scope.chartObject.chart = [];

      for (var x = 0; x < $scope.length; x++) {
        dynamicData.push({
          c: [
            {v: String($scope.chartObject.http[x][0])},
            {v: $scope.chartObject.http[x][1]}
          ]
        });
      }
      console.log(dynamicData);

      $scope.chartObject.data = {
        cols: [
          {id: 'h', label: 'Hour', type: 'string'},
          {id: 'i', label: 'Impressions', type: 'number'}
        ],
        rows: dynamicData
      };

      $scope.chartObject.options = {
        "legend": {
          "position": "top"
        },
        "bar": {
          "groupWidth": "75%"
        }
      };
      $scope.chartObject.formatters = {
        "number": [{
          columnNumber: 0,
          "decimalSymbol": ".",
          "groupingSymbol": ","
        },
          {
            columnNumber: 1,
            "decimalSymbol": ".",
            "groupingSymbol": ","
          }]
      };
    }

I am trying to format the numbers in the thousands and to make the y-axis go 0, 500, 1,000, 1,500, 2,000.

Thank you!

**Comment by Balrog30** [comment]
The only thing I see is that while you're setting the second column of your DataTable as type number, the values you are passing are strings.  Try removing the quotes from the number values and see if that does anything.

As for your y-axis markers, there are option settings to manually set the interval of markers on the axes, just check the documentation at https://developers.google.com/chart/interactive/docs/gallery/columnchart#Configuration_Options. I think the options you are looking for are vAxis.ticks, vAxis.maxValue, vAxis.minValue, and possibly vAxis.format.  vAxis.format would be unnecessary if you give vAxis.Ticks an array of objects with values and formatted values.  There's an explanation for that in the docs.
