### ISSUE TITLE
Chart not displayed due to error: Cannot read property 'Wa' of null.

### ISSUE THREAD

**Issue by NekDil** [bouil/angular-google-chart#160]
I am plotting a simple bar chart, which used to work fine before. Suddenly it started showing this error:
Chart not displayed due to error: Cannot read property 'Wa' of null. Full error object follows.
Object {id: "google-visualization-errors-9", message: "Cannot read property 'Wa' of null"}
Line numbers shown are ng-google-chart.js:197 and 198
Looks like there is some change in Google visualization API.
Can anyone please help me?

**Comment by bouil** [comment]
Can you share a sample of the problem on Plukr?

**Comment by NekDil** [comment]
It's a app with rails backend JSON API. Frontend Angular controllers get data through $resource service. I don't know how to add this in plunkr, but I can post a snippet here. Here is my controller (CoffeeScript):
```cofeescript
angular.module('irisApp').controller "ProgramsController", ($scope, $routeParams, googleChartApiPromise) ->

  $scope.init = ()->
      programsService = new Programs(serverErrorHandler)
      chart1 = {}
      chart1.type = 'ColumnChart'
      chart1.cssStyle = 'height:200px; width:300px;'
      chart1.data = programsService.score_chart_data($routeParams.program_id)
      chart1.options =
        'title': "Latest Score of Sub Programs"
        'isStacked': 'false'
        'fill': 20
        'displayExactValues': true
        'is3D': 'true'
        'vAxis':
          'title': 'Score'
          'gridlines': 'count': 6
        'hAxis': 
          'title': 'Sub Programs'

      chart1.formatters = {}
      $scope.chart = chart1

```

The errors I get is like this:
![image](https://cloud.githubusercontent.com/assets/945044/6263941/677e14e6-b844-11e4-890e-094b60bcc538.png)

In developer console:
```javascript
Object {id: "google-visualization-errors-9", message: "Cannot read property 'Wa' of null"}
```

Surprisingly the error is gone now, I didn't change anything.

**Comment by NekDil** [comment]
The error is transient. I can see it again. Probably, it has something to do with data availability. Since the data is loaded asynchronously from backend JSON API, it might not get data while plotting chart. Any hint?

**Comment by bouil** [comment]
I advise you to console.log(chart1) before assigning to $scope.chart so you see if your call to your programsService was correct or not.

And as a general advice, the function programsService.score_chart_data($routeParams.program_id) should be designed to be asynchronous : adding a "success" and an "error" handler function, or returning a promise.

**Comment by NekDil** [comment]
Thanks a lot. Using promises solved my problem. Here is the code sample:
```javascript
    score_chart_data: (id, successHandler)->
      deferred = $q.defer()
      $http.get("/api/v1/programs/#{id}/cl_score_chart").success((p) ->
        deferred.resolve(p)
        successHandler?(p)
        p.promise).error(@errorHandler)
```
And in controller
```javascript
    @programsService.score_chart_data($routeParams.program_id).then((data) ->
      $scope.score_chart_data = data
      Log.debug "Got Chart Data #{JSON.stringify($scope.score_chart_data)}"
      $scope.isLoading = true
  
      googleChartApiPromise.then ->
        chart1 = {}
        chart1.type = 'ColumnChart'
        chart1.cssStyle = 'height:200px; width:300px;'
        chart1.data = data.data
        chart1.options =
          'title': "Latest Score of Sub Programs"
          'isStacked': 'false'
          'fill': 20
          'displayExactValues': true
          'is3D': 'true'
          'vAxis':
            'title': 'Score'
            'gridlines': 'count': 6
          'hAxis': 
            'title': 'Sub Programs'
  
        chart1.formatters = {}
        $scope.isLoading = false
        $scope.chart = chart1
```
