### ISSUE TITLE
dynamically inserted charts are not displayed

### ISSUE THREAD

**Issue by siritsch** [bouil/angular-google-chart#161]
I have a main column chart with different bar charts. For each column in the main chart I generate a detail chart. 
The html looks like
            <tr ng-repeat="category in Categories">
                <td><div class="Vertical">Functional Testing</div></td>
                <td><div google-chart id="{{category.id}}" style="width: 1400px; height: 300px"></div></td>
            </tr>

Inside my controller I have a function for generating the detail charts:
    function loadTestFolderChart(Release, Cycle, Folder) {
        var catChart = {};
        catChart.options = {
            'isStacked': true, 'legend': 'top',
            'hAxis': { 'title': 'Test Sets' },
            'vAxis': { 'textStyle': { 'fontSize': '12' } },
            'chartArea': { 'width': '60%' },
            'series': [{ 'color': '#008000', 'visibleInLegend': true }, { 'color': '#FF8000', 'visibleInLegend': true }, { 'color': '#FF0000', 'visibleInLegend': true }, { 'color': '#FFFF00', 'visibleInLegend': true }, { 'color': '#00FFFF', 'visibleInLegend': true }],
            'orientation': 'vertical'
        };
        catChart.type = "ColumnChart";

        var categoryXml = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>" +
                    "<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">" +
                      "<soap:Body>" +
                          "<TestFolders xmlns=\"volkswagen.aftersales.qmc\"><Release>" + Release + "</Release><Cycle>" + Cycle + "</Cycle><Category>" + Folder + "</Category></TestFolders>" +
                       "</soap:Body>" +
                    "</soap:Envelope>";

        $http({
            method: 'POST',
            url: BASE_URL,
            headers: {
                'Content-Type': 'text/xml;charset=ISO-8859-1',
                'SOAPAction': 'volkswagen.aftersales.qmc/TestCategories',
                'Accept': 'text/xml'
            },
            data: catChartXml
        }).
        success(function (data) {
            var x2js = new X2JS();
            var objJsonXml = x2js.xml_str2json(data);
            var response = objJsonXml.Envelope.Body.TestCategoriesResponse.TestCategoriesResult;
            var objJson = eval('(' + response + ')');

            if (objJson != null) {
                var chartFolder = Folder.replace(' ', '_');
                var id = Folder + 'Chart';
                var div = document.getElementById(id);
                var chartAttr = document.createAttribute('chart');
                chartAttr.value = chartFolder;
                div.attributes.setNamedItem(chartAttr);
                catChart.data = objJson;
                var model = $parse(chartFolder);
                model.assign($scope, catChart);
                //$scope[chartFolder].drawAsync();
            }
        });

I get all the results back from the server, but the detail charts get not displayed. The 'parent' div remains empty.
<div google-chart="" id="Benutzer TQANBV2Chart" style="width: 1400px; height: 300px" class="ng-isolate-scope" chart="Benutzer_TQANBV2"></div>

In my pure Javascript version without the directive everything works fine.

**Comment by Balrog30** [comment]
I'm on my phone so it's a little difficult to process all those lines of code, but the bit near the bottom that creates an element is a very un-angular way to do this.  I would personally have the elements for the detail charts in place as part of your page or view template and hide them with an ng-if directives until the data is available.  DOM manipulation in controllers is frowned upon for testability reasons, but I also have no idea how AngularJS is going to handle compilation for directives that you're manually inserting (and I'm not even sure that your inserted elements have the right attributes if it did compile properly).

**Comment by siritsch** [comment]
I can not have the detail charts statically in my page and hide or show
them with ng-if, because the number of detail charts may vary depending on
how many categories are part of the main chart.
The DOM manipulation I only did to avoid an angular exception in the
ng-google-chart element. Originally I had something like <div
ng-google-chart chart="{{category.Name}}" id={{category.id}}>. The
exception occured when assigning the chart attribute. So I added the chart
attribute via DOM manipilation.
In the debugger I could see that the chart attribute has been created
correctly. The tricky thing was to create a scope variable (the chart name)
from the value of a string variable. Thats where I used var model =
$parse(Folder) and then model.assign($scope,chart). But none of the detail
charts were displayed only the main chart. The div elements for the detail
charts were also created but they were empty.

2015-02-23 21:20 GMT+01:00 Nicholas Bering <notifications@github.com>:

**Comment by Balrog30** [comment]
I would probably do something like this:

```HTML
<!-- view.html -->
<div google-chart chart="chart" ng-repeat="chart in detailCharts"></div>
```
```JavaScript
//view.controller.js
(function(){
  angular.module('myApp', [])
    .controller('ViewController', ViewController);

  ViewController.$inject = ['$scope', 'myDataService'];

  function ViewController($scope, myDataService){
    $scope.detailCharts = [];

    Init();
    
    function Init(){
      myDataService.getData().then(successCallback);
    }
    
    function successCallback(result){
      //result is an array of datasets formatted for the charts api
      var i;
      var newChart;
      for (i=0; i<result.length; i++){
        newChart = {};
        //Do whatever you need to process the data into something the charts API can handle
        newChart.data = result[i]
        newChart.type = 'BarChart';
        newChart.options = {}; //some options
        //use angular.copy() to dereference the object so that the loop doesn't overwrite your values
        $scope.detailCharts.push(angular.copy(newChart));
      }
    }
})();

//myDataService.factory.js
(function(){
  angular.module('myApp')
    .factory('myDataService', myDataServiceFactory);

    myDataServiceFactory.$inject = ['$http'];

    function myDataServiceFactory($http){
      var myDataService = {
        getData: function(catChartXml){
          //use promise chaining to process the http response before passing to the controller
          return $http({
            method: 'POST',
            url: BASE_URL,
            headers: {
              'Content-Type': 'text/xml;charset=ISO-8859-1',
              'SOAPAction': 'volkswagen.aftersales.qmc/TestCategories',
              'Accept': 'text/xml'
            },
            data: catChartXml
            }).then(successCallback);
          }
        }

        function successCallback(data){
          var x2js = new X2JS();
          var objJsonXml = x2js.xml_str2json(data);
          var response = objJsonXml.Envelope.Body.TestCategoriesResponse.TestCategoriesResult;
          var objJson = eval('(' + response + ')');
          return objJson;
        }

        return myDataService;
    }
})();
```

Probably the most code I've ever composed inside a GitHub issue, so don't expect this to actually run.  Basically I've made the chart as an ng-repeat.  You can nest ng-repeats so even if you have a tiered setup, this should work.  If you need to keep track of a title or some other properties that are not part of your chart data, just stick it on your chart object, or nest the chart object in some more complex structure.

I also moved the fetching and processing of data to a service so as not to clutter up the controller.  Has the added side-effect of being more reusable, and can be mocked for unit tests.  Forgive me if I totally messed up on the service.  I've never used AngularJS with a Soap service.  I just kind of copied some of your code into the service's success callback.

You can wrap pretty much any regular JavaScript in an Angular service to take advantage of dependency injection.  For example, you could build a service that returns your X2JS library.

All this being said, if you're got this working in pure JavaScript, is there some reason you really need to turn it into an AngularJS application?  Are you converting an existing app, or trying to figure out how to add this as a new feature in an Ang

**Comment by Balrog30** [comment]
I would probably do something like this:

```HTML
<!-- view.html -->
<div google-chart chart="chart" ng-repeat="chart in detailCharts"></div>
```
```JavaScript
//view.controller.js
(function(){
  angular.module('myApp', [])
    .controller('ViewController', ViewController);

  ViewController.$inject = ['$scope', 'myDataService'];

  function ViewController($scope, myDataService){
    $scope.detailCharts = [];

    Init();
    
    function Init(){
      myDataService.getData().then(successCallback);
    }
    
    function successCallback(result){
      //result is an array of datasets formatted for the charts api
      var i;
      var newChart;
      for (i=0; i<result.length; i++){
        newChart = {};
        //Do whatever you need to process the data into something the charts API can handle
        newChart.data = result[i]
        newChart.type = 'BarChart';
        newChart.options = {}; //some options
        //use angular.copy() to dereference the object so that the loop doesn't overwrite your values
        $scope.detailCharts.push(angular.copy(newChart));
      }
    }
})();

//myDataService.factory.js
(function(){
  angular.module('myApp')
    .factory('myDataService', myDataServiceFactory);

    myDataServiceFactory.$inject = ['$http'];

    function myDataServiceFactory($http){
      var myDataService = {
        getData: function(catChartXml){
          //use promise chaining to process the http response before passing to the controller
          return $http({
            method: 'POST',
            url: BASE_URL,
            headers: {
              'Content-Type': 'text/xml;charset=ISO-8859-1',
              'SOAPAction': 'volkswagen.aftersales.qmc/TestCategories',
              'Accept': 'text/xml'
            },
            data: catChartXml
            }).then(successCallback);
          }
        }

        function successCallback(data){
          var x2js = new X2JS();
          var objJsonXml = x2js.xml_str2json(data);
          var response = objJsonXml.Envelope.Body.TestCategoriesResponse.TestCategoriesResult;
          var objJson = eval('(' + response + ')');
          return objJson;
        }

        return myDataService;
    }
})();
```

Probably the most code I've ever composed inside a GitHub issue, so don't expect this to actually run.  Basically I've made the chart as an ng-repeat.  You can nest ng-repeats so even if you have a tiered setup, this should work.  If you need to keep track of a title or some other properties that are not part of your chart data, just stick it on your chart object, or nest the chart object in some more complex structure.

I also moved the fetching and processing of data to a service so as not to clutter up the controller.  Has the added side-effect of being more reusable, and can be mocked for unit tests.  Forgive me if I totally messed up on the service.  I've never used AngularJS with a Soap service.  I just kind of copied some of your code into the service's success callback.

You can wrap pretty much any regular JavaScript in an Angular service to take advantage of dependency injection.  For example, you could build a service that returns your X2JS library.

All this being said, if you're got this working in pure JavaScript, is there some reason you really need to turn it into an AngularJS application?  Are you converting an existing app?

**Comment by siritsch** [comment]
Yes I'm migrating an existing JavaScript app to AngularJS. The JavaScript app is quite complex because  most elements are inserted by DOM manipulation. With the Angular template mechanism I hope to reduce the complexity.

Now I got all the charts working with your directive. So this issue can be closed. I sill only have one problem. Part of my app is also a defect Table of type google.visualization.Table. When I select a row in the table a detail table is created, based on the contents of the selected row. I got this table also displayed with the directive, but I'm struggling to get my custom selection handler called properly. The directive calls $scope.onSelect(selection) or $scope.select(selection).
When setting 
"&lt;!-- view.html --&gt;
&lt;div google-chart chart="defectTable" select="categorySelect()"&gt;&lt;/div&gt;"
and 
$scope.categorySelect = function(selection) {
} 
in the controller, the function categorySelect is called but without the selection argument.  

As the select attribute is deprecated I also tried to use &lt;div google-chart chart="defectTable" onSelect="categorySelect()"&gt;&lt;/div&gt; but then the function categorySelect was not called at all.

So how can I get my custom selection handler called with the selection argument.

**Comment by Balrog30** [comment]
Sorry for the confusion on that one.  In JavaScript code directives and attributes are referred to by camel case (onSelect) and in html they are referred to in snake case (on-select).  I wrote the message as onSelect when I really should have written it as on-select.  I'll see what I can come up with for an answer to your parameter problem when I'm at an actual computer instead of my cell phone.

**Comment by Balrog30** [comment]
Ok, your missing value comes from two things.  First, your `on-select=categorySelect()` needs to have a parameter in the function call.  I believe this is where angular handles the injection of the value(s) requested by the function.  Second, the parameter name does matter.  For reasons I do not fully understand, when calling functions from the isolate scope of the directive that are referenced from other areas of the application, names are applied to the values in a manner very similar to dependency injection in other areas of angular.  Therefore your parameter must be called `selectedItem` because that is how it is being passed from the chart directive.  If you are working from the gh-pages branch instead of master, you may also have the option to receive `selectedItems` instead, which returns an array of items so that you can work with multi-item selections.

**Comment by siritsch** [comment]
Thanks for your help. Indeed now it works!

2015-03-06 16:31 GMT+01:00 Nicholas Bering <notifications@github.com>:
