### ISSUE TITLE
chart not displaying

### ISSUE THREAD

**Issue by c0debreaker** [bouil/angular-google-chart#162]
I'm not sure what I'm doing wrong. I've been using your library for almost a year now and it's working great. Today, I created a new controller and in this controller, it will plot a simple chart. The variable I am using is

```
$scope.globalChart
```

On my template, I have this html code

```
<div google-chart chart="globalChart"></div>
```

The value that is assigned to $scope.globalChart is https://gist.github.com/c0debreaker/c6e3dd7262c6195ced33

However, it's not displaying anything. There is no error too which is very hard to troubleshoot. I've also manually used an example working ng-google-chart code I found from your demo plunker but it's also not displaying it. I'm very sure the template is being used because when I modify the template, I see the modifications. It's making me nuts.

I've also used $rootScope.globalChart in the controller and $root.globalChart in the template, no luck too! This is very weird.

**Comment by c0debreaker** [comment]
I changed it to this

```
$timeout(function() {
    console.log('executing globalChart');
    $scope.globalChart = plotGlobalUsers(prepareGoogleChartData(spreadsheet));
}, 5000);
```
It got executed and I saw "executing globalChart" but the graph still didn't get rendered :(

**Comment by c0debreaker** [comment]
I changed it to this hoping google chart will complain but still no error. There is something I'm not doing right

```
$timeout(function() {
    console.log('executing globalChart');
    $scope.globalChart = undefined;
}, 5000);
```

**Comment by Balrog30** [comment]
Is the module loaded in your app module declaration?

**Comment by c0debreaker** [comment]
Yes. Other charts are working perfectly.

**Comment by Balrog30** [comment]
In the template, add
```HTML
<pre>{{ globalChart | json:true }}</pre>
```
Make sure you add this on the same level of the DOM as your chart.  This will tell you if you having a scoping conflict (I sometimes had issues with this when using UI-bootstrap tabs or similar directives)

**Comment by c0debreaker** [comment]
Ok, I'm going to try it now

**Comment by Balrog30** [comment]
By the way, I'm on my phone so typing errors are a pain to fix.

**Comment by c0debreaker** [comment]
:)

**Comment by c0debreaker** [comment]
I added that code and refreshed. After 5 seconds since I used $timeout 5000, the json got displayed. This is the json that got displayed on the screen - https://gist.github.com/c0debreaker/868de5d33664aa42a2cc

I also verified that json output in jsonlint.com, it's valid

**Comment by c0debreaker** [comment]
This is a screenshot of it - http://i.imgur.com/goZFbTp.png

**Comment by Balrog30** [comment]
If you inspect the page with your browser's dev tools to look at the active DOM, is the dive with your chart directive appearing, and if so is there anything being rendered inside that div?

**Comment by c0debreaker** [comment]
Nothing appears inside it versus my other charts that are working - http://i.imgur.com/wYvrlhs.png

**Comment by c0debreaker** [comment]
I've also removed it out of the ui-bootstrap classes. I put it on the topmost of my html template. Still didn't help

**Comment by c0debreaker** [comment]
Also, I put the generated json data into one of your plunker demo. It worked. However, I have to change one type from datetime to string. I also changed it from my original code. It still didn't help.  Using my data - http://plnkr.co/edit/QHzgV6mXgy0LvaW7zbux?p=preview

**Comment by Balrog30** [comment]
What version of angular are you using?

**Comment by c0debreaker** [comment]
AngularJS v1.2.21 - other charts are working fine

**Comment by c0debreaker** [comment]
I'll continue troubleshooting later since I have drive wife to some place. I'll keep you posted. Thanks again.

**Comment by Balrog30** [comment]
Finally got to a computer and spotted something right away.  You have options for width and height set to zero, so Charts API may be skipping rendering it since there will be nothing displayed anyway.  The plunker you were using was overriding that a bit with CSS, maybe it was then displaying it?

**Comment by c0debreaker** [comment]
Finally leaving in few minutes. :) I commented out width and height but it didn't help. A google chart developer told me to use 0 value if I wanted it to have a dynamic size when we resize the browser. I've been using 0 value even on my other charts. Ok, catch you later. Thanks again.

**Comment by Balrog30** [comment]
I'm at a loss... The next step I would take is to start setting breakpoints in ng-google-chart.js to see what values it is running with.  The directive runs with an isolate scope so something could be going wrong in the binding of values from one scope to the next.  It seems very unlikely, but anything is possible with scope.

**Comment by c0debreaker** [comment]
Just got home. I will try that.

**Comment by c0debreaker** [comment]
It's working now after using your latest version!!!!  I was using version 0.8.

**Comment by c0debreaker** [comment]
Thanks for all the help! I learned a lot in troubleshooting. :)
