### ISSUE TITLE
regionClick event listener for GeoChart

### ISSUE THREAD

**Issue by d0coat01** [bouil/angular-google-chart#166]
https://developers.google.com/chart/interactive/docs/gallery/geochart#Regions

I tried adding an event listener to the draw() function to try to get some sort of response for the regionClick event, but no luck. 

Event Listener
~~~
google.visualization.events.addListener($scope.chartWrapper, 'regionClick', function(r) {
    console.log(r);
  });
~~~
Chart variable
~~~
 $scope.chart = {
		  type: "GeoChart",
		  data: [
                        ['Locale','Visits'],
                        ['United States', 100],
                        ['Germany', 200]
                  ],
		  options: {
		      width: 600,
		      height: 300,
		      chartArea: {left:10,top:10,bottom:0,height:"100%"},
		      colorAxis: {colors: ['#aec7e8', '#1f77b4']},
		      displayMode: 'regions',
		      enableRegionInteractivity: true
		  }
	 };
~~~

**Comment by Balrog30** [comment]
The ChartWrapper itself has a limited subset of events that it supports, but you can use the ChartWrapper.getChart() function to get the underlying GeoChart object and apply the event listener to that.  Let me know if you have any trouble with this... I can write a code sample but I'm on my phone write now.

**Comment by d0coat01** [comment]
Thanks for the response. I added an event listener using the on-ready="readyHandler(chartWrapper)" method detailed in [#55](https://github.com/bouil/angular-google-chart/issues/55). 

Unfortunately, the 'regionClick' event listener either isn't working or it somehow isn't firing. Here is a [plunker](http://plnkr.co/edit/kmuyKG?p=preview) of the geo chart. My readyHandler function:
~~~
  $scope.readyHandler = function(chartWrapper) {
    $window.google.visualization.events.addListener(chartWrapper, 'regionClick', function(r) {
      $scope.regionClick(r);
    });
  }
  $scope.regionClick = function(region) {
    alert(region);
  }
~~~

**Comment by Balrog30** [comment]
Try this:
```
$scope.readyHandler = function(chartWrapper) {
    $window.google.visualization.events.addListener(chartWrapper.getChart(), 'regionClick', function(r) {
      $scope.regionClick(r);
    });
  }
  $scope.regionClick = function(region) {
    alert(region);
  }
```

It grabs the underlying geochart object from the chartWrapper and binds the event callback to this object.  This works because the chartWrapper itself only supports a generic set of events that apply to most of the chart types.

**Comment by d0coat01** [comment]
You are a legend. Thank you. Works just like it should.  

For those interested, here is a working [plunker](http://plnkr.co/edit/kmuyKG?p=preview) for a regionClick() event in a GeoChart.
