### ISSUE TITLE
Accept array, not only DataTable

### ISSUE THREAD

**Issue by mgsstms** [bouil/angular-google-chart#167]
In https://github.com/bouil/angular-google-chart/issues/83 you provided this piece of the code:

<pre>
if ($scope.chart.data instanceof google.visualization.DataTable)
    dataTable = $scope.chart.data;  //Should be doing this.
else if (angular.isArray($scope.chart.data))
    dataTable = google.visualization.arrayToDataTable($scope.chart.data);
else
    dataTable = new google.visualization.DataTable($scope.chart.data, 0.5); //Doing this instead.
</pre>
Is it possible it be as the part of the directive?

**Comment by Balrog30** [comment]
I am not sure what you're asking for, but I believe the way we have it set now let's the Charts API sort out the Data/DataTable.  The change from how it was done before was to prevent double-draws which were hurting performance for people with large datasets.  

The Charts API does support Arrays as input.

**Comment by mgsstms** [comment]
Thank you. My fault ((
