### ISSUE TITLE
RequireJs Support

### ISSUE THREAD

**Issue by andyzeli** [bouil/angular-google-chart#171]
Hey All,

I am wondering if there are any examples of using this directive with RequireJs. I cannot seem to get it to work. 
snippet of code that doesnt work: 

define(['angular', 'jquery',  'angular-google-chart', './routes', './Chart/ChartCtrl'], function(angular) {
  'use strict';

  return angular.module('dashboard', ['ngRoute', 'googlechart', 'dashboard.routes', 'dashboard.chart.ctrls']);
});

**Comment by Balrog30** [comment]
I may be out of date on this one, but I do not believe that angular officially supports RequireJS.  I know there are workarounds that can help make it happen.  The main problem is that Angular's Dependency Injection requires that all the code files be loaded when angular is bootstrapped.

Is this something you are already using in your project, or is this the first module you are trying to load with RequireJS?

**Comment by andyzeli** [comment]
Thanks for the response. yes, I already have Require and Angular trying to play nicely. you can look at an example project here https://github.com/mariussoutier/play-angular-require-seed/tree/master/app/assets/javascripts . Theres a few more moving parts in that for JVM land you download javascript JARs from a CDN. Its difficult to reason about why the module isnt being loaded. for most 3rd party libraries its as simple as adding the dependency to both Require and Angular. So if you have a file named myThing.js with a angular module called 'mymodule', you just do as above: add the file to the require dependency and the module to the returned super module as a dependency

**Comment by Balrog30** [comment]
What is the result of what you are doing?  Is it throwing any errors?  Is it loading but not functioning?

**Comment by andyzeli** [comment]
loading but not functioning. i suppose this may be an unanswerable issue (environment related)

**Comment by andyzeli** [comment]
update: I got it to work with this missing piece - adding angular as dependency in RequireJs shim!
 shim: { 
      'angular-google-chart': ['angular'],
}
glad i can use this library! thanks
